### ISSUE TITLE
Port improved E2E tests from RC Operator

### ISSUE THREAD

**Issue by edavidj** [appsody/appsody-operator#269]
Migrate some of the e2e test updates over from the RC operator, identical to OL operator issue [#156](https://github.com/OpenLiberty/open-liberty-operator/issues/156).

- [x] Knative test updates ([#108](https://github.com/application-stacks/runtime-component-operator/pull/108))
- [x] Imagestream test
- [x] Cert Manager test (once [#177](https://github.com/application-stacks/runtime-component-operator/issues/114) is resolved)
- [x] Updates from [#77](https://github.com/application-stacks/runtime-component-operator/pull/77), this will be merged into RC later this week but can begin porting now.
- [x] Port changes that allow for running Minishift jobs as well as OCP ([#104](https://github.com/application-stacks/runtime-component-operator/pull/104))

**Comment by InfTkm** [comment]
Config Map tests are failing on the Travis build. I will take a look after I finish the migration.
